// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3tc36i2oRXIeRmKQSYsdMoVrrS6E27Vs',
    appId: '1:241915420751:web:7c2e48674ae645767d0a3a',
    messagingSenderId: '241915420751',
    projectId: 'izazproject',
    authDomain: 'izazproject.firebaseapp.com',
    storageBucket: 'izazproject.firebasestorage.app',
    measurementId: 'G-NNN7T1HTE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD98lKXMf4yLxXL6fUyXch9zNoqQAOPcw',
    appId: '1:241915420751:android:1ae713bb014677467d0a3a',
    messagingSenderId: '241915420751',
    projectId: 'izazproject',
    storageBucket: 'izazproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhPSpGRai54KZbYkUno4WGZXZSBRqZ_VM',
    appId: '1:241915420751:ios:63c4ccda6666d62a7d0a3a',
    messagingSenderId: '241915420751',
    projectId: 'izazproject',
    storageBucket: 'izazproject.firebasestorage.app',
    iosBundleId: 'com.example.izazproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhPSpGRai54KZbYkUno4WGZXZSBRqZ_VM',
    appId: '1:241915420751:ios:63c4ccda6666d62a7d0a3a',
    messagingSenderId: '241915420751',
    projectId: 'izazproject',
    storageBucket: 'izazproject.firebasestorage.app',
    iosBundleId: 'com.example.izazproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3tc36i2oRXIeRmKQSYsdMoVrrS6E27Vs',
    appId: '1:241915420751:web:d331056168e420907d0a3a',
    messagingSenderId: '241915420751',
    projectId: 'izazproject',
    authDomain: 'izazproject.firebaseapp.com',
    storageBucket: 'izazproject.firebasestorage.app',
    measurementId: 'G-PESN29RC84',
  );
}
